appium_cases = [
  { "id": "TC001", "description": "Verify app launch to login screen transition", "key": "loginEmailVisible", "category": "Functional Testing" },
  { "id": "TC002", "description": "Verify valid user login validation", "key": "validUserLogin", "category": "Functional Testing" },
  { "id": "TC003", "description": "Verify invalid login credentials show error toast", "key": "invalidLoginError", "category": "Functional Testing" },
  { "id": "TC004", "description": "Verify navigation to signup screen", "key": "navigateToSignup", "category": "Functional Testing" },
  { "id": "TC005", "description": "Verify new donor registration flow validation", "key": "navigateToSignup", "category": "Functional Testing" },
  { "id": "TC006", "description": "Verify password recovery verification code field", "key": "resetEmailVisible", "category": "Functional Testing" },
  { "id": "TC007", "description": "Verify dashboard summary numbers match mock counts", "key": "dashboardReportCountVisible", "category": "Functional Testing" },
  { "id": "TC008", "description": "Verify upload profile photo photo chooser opens", "key": "uploadScreenOpen", "category": "Functional Testing" },
  { "id": "TC009", "description": "Verify contact phone field digit input rules", "key": "uploadScreenOpen", "category": "Functional Testing" },
  { "id": "TC010", "description": "Verify blood request submittal validations", "key": "uploadScreenOpen", "category": "Functional Testing" },
  { "id": "TC011", "description": "Verify drawer navigation menu links are clickable", "key": "historyNavVisible", "category": "Functional Testing" },
  { "id": "TC012", "description": "Verify consistency of font size across screens", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC013", "description": "Verify color contrast for readability", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC014", "description": "Verify button hover effects and styling", "key": "loginButtonVisible", "category": "UI/UX Testing" },
  { "id": "TC015", "description": "Verify clear error messages for invalid input format", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC016", "description": "Verify smooth transitions between dashboard tabs", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC017", "description": "Verify image loading placeholders for donor profiles", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC018", "description": "Verify form field alignment on registration screens", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC019", "description": "Verify dark mode UI consistency across widgets", "key": "loginPasswordVisible", "category": "UI/UX Testing" },
  { "id": "TC020", "description": "Verify glassmorphism effects on cards layout", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC021", "description": "Verify app behavior on small browser viewports", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC022", "description": "Verify app behavior on tablets/large display screens", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC023", "description": "Verify app compatibility with Android 10 mobile viewports", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC024", "description": "Verify app compatibility with Android 13 mobile viewports", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC025", "description": "Verify app behavior on different screen aspect ratios", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC026", "description": "Verify app fonts scaling with system browser options", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC027", "description": "Verify background tasks on low-end hardware performance", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC028", "description": "Verify app launch time on cold start browser cache", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC029", "description": "Verify interaction with system navigation gestures", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC030", "description": "Verify app behavior when low storage warnings are active", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC031", "description": "Measure home screen load time on normal network", "key": "loginEmailVisible", "category": "Performance Testing" },
  { "id": "TC032", "description": "Verify app performance during donor list infinite scroll", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC033", "description": "Verify CPU usage during heavy map interactions", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC034", "description": "Verify memory usage during image loading and uploading", "key": "uploadScreenOpen", "category": "Performance Testing" },
  { "id": "TC035", "description": "Verify network usage optimization under offline states", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC036", "description": "Measure login API response time during heavy load", "key": "loginEmailVisible", "category": "Performance Testing" },
  { "id": "TC037", "description": "Measure search query execution time on dashboard search", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC038", "description": "Verify app behavior during network disconnection states", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC039", "description": "Verify frame rate during animations on dashboard", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC040", "description": "Verify battery consumption during active location tracking", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC041", "description": "Verify data encryption in local storage fields", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC042", "description": "Verify HTTPS enforcement for all API endpoints", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC043", "description": "Verify session timeout and auto-logout mechanisms", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC044", "description": "Verify protection against SQL injection on forms", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC045", "description": "Verify sensitive data masking in logging outputs", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC046", "description": "Verify biometric authentication prompts configurations", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC047", "description": "Verify SSL pinning implementation rules", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC048", "description": "Verify secure password hashing algorithms are used", "key": "loginPasswordVisible", "category": "Security Testing" },
  { "id": "TC049", "description": "Verify prevention of rooted device access to account settings", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC050", "description": "Verify OAuth2 token security during message chat session", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC051", "description": "Verify GET /donors returns correct data format payload", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC052", "description": "Verify POST /requests handles valid request inputs", "key": "uploadScreenOpen", "category": "API Testing" },
  { "id": "TC053", "description": "Verify API returns 401 for unauthorized access attempts", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC054", "description": "Verify API rate limiting rules on fast clicks", "key": "loginEmailVisible", "category": "API Testing" },
  { "id": "TC055", "description": "Verify API error response for invalid JSON payloads", "key": "loginEmailVisible", "category": "API Testing" },
  { "id": "TC056", "description": "Verify JSON schema validation rules on fetch operations", "key": "loginEmailVisible", "category": "API Testing" },
  { "id": "TC057", "description": "Verify payload size limits validation constraints", "key": "uploadScreenOpen", "category": "API Testing" },
  { "id": "TC058", "description": "Verify API versioning header values in headers", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC059", "description": "Verify concurrent API requests handling on dashboard", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC060", "description": "Verify API latency in different regional locations", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC061", "description": "Verify user data persistence in local indexed database", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC062", "description": "Verify real-time updates for donor availability fields", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC063", "description": "Verify database indexing for optimized searches on list", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC064", "description": "Verify data consistency across multi-role accounts settings", "key": "loginEmailVisible", "category": "Database Testing" },
  { "id": "TC065", "description": "Verify transaction integrity for blood requests submission", "key": "uploadScreenOpen", "category": "Database Testing" },
  { "id": "TC066", "description": "Verify automatic backup and recovery triggers", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC067", "description": "Verify data migration scripts on app version upgrade", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC068", "description": "Verify field-level integrity rules for blood groups", "key": "loginEmailVisible", "category": "Database Testing" },
  { "id": "TC069", "description": "Verify query performance for large history listings", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC070", "description": "Verify cleanup of expired blood requests automatically", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC071", "description": "Verify screen reader support for all navigation buttons", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC072", "description": "Verify touch target sizes meet accessibility standards", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC073", "description": "Verify high contrast theme support for low vision users", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC074", "description": "Verify text scaling without layout breaking on profile", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC075", "description": "Verify description alt text for images and badges", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC076", "description": "Verify focus indicators for interactive buttons list", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC077", "description": "Verify keyboard navigation support for registration flow", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC078", "description": "Verify captions for key video and help content displays", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC079", "description": "Verify clear error announcements in screen reader actions", "key": "loginPasswordVisible", "category": "Accessibility Testing" },
  { "id": "TC080", "description": "Verify accessible name for icon buttons and navigation elements", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC081", "description": "Verify app behavior on incoming calls", "key": "loginEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC082", "description": "Verify app behavior during network change", "key": "loginEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC083", "description": "Verify push notification click-through behavior", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC084", "description": "Verify app state preservation during backgrounding", "key": "loginEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC085", "description": "Verify camera integration for profile settings", "key": "uploadScreenOpen", "category": "Mobile-Specific Testing" },
  { "id": "TC086", "description": "Verify location permission handling dynamically", "key": "uploadScreenOpen", "category": "Mobile-Specific Testing" },
  { "id": "TC087", "description": "Verify deep link processing inside Android intent", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC088", "description": "Verify orientation change handling triggers layout rebuild", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC089", "description": "Verify offline data sync functionality and storage sync", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC090", "description": "Verify app interaction with other system applications", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC091", "description": "Verify existing bug fix: Hospital dropdown select issue", "key": "loginEmailVisible", "category": "Regression Testing" },
  { "id": "TC092", "description": "Verify existing bug fix: Login session persistence", "key": "loginEmailVisible", "category": "Regression Testing" },
  { "id": "TC093", "description": "Verify legacy features compatibility with layout configurations", "key": "loginEmailVisible", "category": "Regression Testing" },
  { "id": "TC094", "description": "Verify user flow: App launch to page selections", "key": "loginEmailVisible", "category": "Regression Testing" },
  { "id": "TC095", "description": "Verify registration fields validation rules", "key": "loginPasswordVisible", "category": "Regression Testing" },
  { "id": "TC096", "description": "Full Flow: User registration to blood request submission", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC097", "description": "Full Flow: Donor registration to request acceptance", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC098", "description": "Full Flow: Hospital login to blood stock management", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC099", "description": "Full Flow: Admin dashboard monitoring to report generation", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC100", "description": "Full Flow: Guest search to login prompt to request matching", "key": "profileNavVisible", "category": "End-to-End Testing" }
]
