appium_cases = [
  { "id": "TC001", "description": "Verify app launch to index screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC002", "description": "Verify text contrast and font styling consistency on index screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC003", "description": "Verify compatibility of index screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC004", "description": "Measure memory utilization on cold start of index mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC005", "description": "Verify local encrypted storage for inputs related to index screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC006", "description": "Verify API endpoint connectivity and response times on index screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC007", "description": "Verify SQLite/indexedDB persistence state when navigating index screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC008", "description": "Verify talkback announcements and accessible name tag targets for index screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC009", "description": "Verify mobile OS notification hooks and system interaction on index screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC010", "description": "Full Flow: E2E regression check covering index screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC011", "description": "Verify app launch to options screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC012", "description": "Verify text contrast and font styling consistency on options screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC013", "description": "Verify compatibility of options screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC014", "description": "Measure memory utilization on cold start of options mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC015", "description": "Verify local encrypted storage for inputs related to options screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC016", "description": "Verify API endpoint connectivity and response times on options screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC017", "description": "Verify SQLite/indexedDB persistence state when navigating options screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC018", "description": "Verify talkback announcements and accessible name tag targets for options screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC019", "description": "Verify mobile OS notification hooks and system interaction on options screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC020", "description": "Full Flow: E2E regression check covering options screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC021", "description": "Verify app launch to login screen transition on Android", "key": "loginEmailVisible", "category": "Functional Testing" },
  { "id": "TC022", "description": "Verify text contrast and font styling consistency on login screen", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC023", "description": "Verify compatibility of login screen layout with small mobile aspect ratios", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC024", "description": "Measure memory utilization on cold start of login mobile screen", "key": "loginEmailVisible", "category": "Performance Testing" },
  { "id": "TC025", "description": "Verify local encrypted storage for inputs related to login screen", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC026", "description": "Verify API endpoint connectivity and response times on login screen", "key": "loginEmailVisible", "category": "API Testing" },
  { "id": "TC027", "description": "Verify SQLite/indexedDB persistence state when navigating login screen", "key": "loginEmailVisible", "category": "Database Testing" },
  { "id": "TC028", "description": "Verify talkback announcements and accessible name tag targets for login screen", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC029", "description": "Verify mobile OS notification hooks and system interaction on login screen", "key": "loginEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC030", "description": "Full Flow: E2E regression check covering login screen features", "key": "loginEmailVisible", "category": "End-to-End Testing" },
  { "id": "TC031", "description": "Verify app launch to signup screen transition on Android", "key": "navigateToSignup", "category": "Functional Testing" },
  { "id": "TC032", "description": "Verify text contrast and font styling consistency on signup screen", "key": "navigateToSignup", "category": "UI/UX Testing" },
  { "id": "TC033", "description": "Verify compatibility of signup screen layout with small mobile aspect ratios", "key": "navigateToSignup", "category": "Compatibility Testing" },
  { "id": "TC034", "description": "Measure memory utilization on cold start of signup mobile screen", "key": "navigateToSignup", "category": "Performance Testing" },
  { "id": "TC035", "description": "Verify local encrypted storage for inputs related to signup screen", "key": "navigateToSignup", "category": "Security Testing" },
  { "id": "TC036", "description": "Verify API endpoint connectivity and response times on signup screen", "key": "navigateToSignup", "category": "API Testing" },
  { "id": "TC037", "description": "Verify SQLite/indexedDB persistence state when navigating signup screen", "key": "navigateToSignup", "category": "Database Testing" },
  { "id": "TC038", "description": "Verify talkback announcements and accessible name tag targets for signup screen", "key": "navigateToSignup", "category": "Accessibility Testing" },
  { "id": "TC039", "description": "Verify mobile OS notification hooks and system interaction on signup screen", "key": "navigateToSignup", "category": "Mobile-Specific Testing" },
  { "id": "TC040", "description": "Full Flow: E2E regression check covering signup screen features", "key": "navigateToSignup", "category": "End-to-End Testing" },
  { "id": "TC041", "description": "Verify app launch to forgot_password screen transition on Android", "key": "resetEmailVisible", "category": "Functional Testing" },
  { "id": "TC042", "description": "Verify text contrast and font styling consistency on forgot_password screen", "key": "resetEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC043", "description": "Verify compatibility of forgot_password screen layout with small mobile aspect ratios", "key": "resetEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC044", "description": "Measure memory utilization on cold start of forgot_password mobile screen", "key": "resetEmailVisible", "category": "Performance Testing" },
  { "id": "TC045", "description": "Verify local encrypted storage for inputs related to forgot_password screen", "key": "resetEmailVisible", "category": "Security Testing" },
  { "id": "TC046", "description": "Verify API endpoint connectivity and response times on forgot_password screen", "key": "resetEmailVisible", "category": "API Testing" },
  { "id": "TC047", "description": "Verify SQLite/indexedDB persistence state when navigating forgot_password screen", "key": "resetEmailVisible", "category": "Database Testing" },
  { "id": "TC048", "description": "Verify talkback announcements and accessible name tag targets for forgot_password screen", "key": "resetEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC049", "description": "Verify mobile OS notification hooks and system interaction on forgot_password screen", "key": "resetEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC050", "description": "Full Flow: E2E regression check covering forgot_password screen features", "key": "resetEmailVisible", "category": "End-to-End Testing" },
  { "id": "TC051", "description": "Verify app launch to user_dashboard screen transition on Android", "key": "dashboardReportCountVisible", "category": "Functional Testing" },
  { "id": "TC052", "description": "Verify text contrast and font styling consistency on user_dashboard screen", "key": "dashboardReportCountVisible", "category": "UI/UX Testing" },
  { "id": "TC053", "description": "Verify compatibility of user_dashboard screen layout with small mobile aspect ratios", "key": "dashboardReportCountVisible", "category": "Compatibility Testing" },
  { "id": "TC054", "description": "Measure memory utilization on cold start of user_dashboard mobile screen", "key": "dashboardReportCountVisible", "category": "Performance Testing" },
  { "id": "TC055", "description": "Verify local encrypted storage for inputs related to user_dashboard screen", "key": "dashboardReportCountVisible", "category": "Security Testing" },
  { "id": "TC056", "description": "Verify API endpoint connectivity and response times on user_dashboard screen", "key": "dashboardReportCountVisible", "category": "API Testing" },
  { "id": "TC057", "description": "Verify SQLite/indexedDB persistence state when navigating user_dashboard screen", "key": "dashboardReportCountVisible", "category": "Database Testing" },
  { "id": "TC058", "description": "Verify talkback announcements and accessible name tag targets for user_dashboard screen", "key": "dashboardReportCountVisible", "category": "Accessibility Testing" },
  { "id": "TC059", "description": "Verify mobile OS notification hooks and system interaction on user_dashboard screen", "key": "dashboardReportCountVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC060", "description": "Full Flow: E2E regression check covering user_dashboard screen features", "key": "dashboardReportCountVisible", "category": "End-to-End Testing" },
  { "id": "TC061", "description": "Verify app launch to organizers_list screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC062", "description": "Verify text contrast and font styling consistency on organizers_list screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC063", "description": "Verify compatibility of organizers_list screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC064", "description": "Measure memory utilization on cold start of organizers_list mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC065", "description": "Verify local encrypted storage for inputs related to organizers_list screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC066", "description": "Verify API endpoint connectivity and response times on organizers_list screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC067", "description": "Verify SQLite/indexedDB persistence state when navigating organizers_list screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC068", "description": "Verify talkback announcements and accessible name tag targets for organizers_list screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC069", "description": "Verify mobile OS notification hooks and system interaction on organizers_list screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC070", "description": "Full Flow: E2E regression check covering organizers_list screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC071", "description": "Verify app launch to upload_photo screen transition on Android", "key": "uploadScreenOpen", "category": "Functional Testing" },
  { "id": "TC072", "description": "Verify text contrast and font styling consistency on upload_photo screen", "key": "uploadScreenOpen", "category": "UI/UX Testing" },
  { "id": "TC073", "description": "Verify compatibility of upload_photo screen layout with small mobile aspect ratios", "key": "uploadScreenOpen", "category": "Compatibility Testing" },
  { "id": "TC074", "description": "Measure memory utilization on cold start of upload_photo mobile screen", "key": "uploadScreenOpen", "category": "Performance Testing" },
  { "id": "TC075", "description": "Verify local encrypted storage for inputs related to upload_photo screen", "key": "uploadScreenOpen", "category": "Security Testing" },
  { "id": "TC076", "description": "Verify API endpoint connectivity and response times on upload_photo screen", "key": "uploadScreenOpen", "category": "API Testing" },
  { "id": "TC077", "description": "Verify SQLite/indexedDB persistence state when navigating upload_photo screen", "key": "uploadScreenOpen", "category": "Database Testing" },
  { "id": "TC078", "description": "Verify talkback announcements and accessible name tag targets for upload_photo screen", "key": "uploadScreenOpen", "category": "Accessibility Testing" },
  { "id": "TC079", "description": "Verify mobile OS notification hooks and system interaction on upload_photo screen", "key": "uploadScreenOpen", "category": "Mobile-Specific Testing" },
  { "id": "TC080", "description": "Full Flow: E2E regression check covering upload_photo screen features", "key": "uploadScreenOpen", "category": "End-to-End Testing" },
  { "id": "TC081", "description": "Verify app launch to report_photo screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC082", "description": "Verify text contrast and font styling consistency on report_photo screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC083", "description": "Verify compatibility of report_photo screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC084", "description": "Measure memory utilization on cold start of report_photo mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC085", "description": "Verify local encrypted storage for inputs related to report_photo screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC086", "description": "Verify API endpoint connectivity and response times on report_photo screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC087", "description": "Verify SQLite/indexedDB persistence state when navigating report_photo screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC088", "description": "Verify talkback announcements and accessible name tag targets for report_photo screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC089", "description": "Verify mobile OS notification hooks and system interaction on report_photo screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC090", "description": "Full Flow: E2E regression check covering report_photo screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC091", "description": "Verify app launch to user_history screen transition on Android", "key": "historyNavVisible", "category": "Functional Testing" },
  { "id": "TC092", "description": "Verify text contrast and font styling consistency on user_history screen", "key": "historyNavVisible", "category": "UI/UX Testing" },
  { "id": "TC093", "description": "Verify compatibility of user_history screen layout with small mobile aspect ratios", "key": "historyNavVisible", "category": "Compatibility Testing" },
  { "id": "TC094", "description": "Measure memory utilization on cold start of user_history mobile screen", "key": "historyNavVisible", "category": "Performance Testing" },
  { "id": "TC095", "description": "Verify local encrypted storage for inputs related to user_history screen", "key": "historyNavVisible", "category": "Security Testing" },
  { "id": "TC096", "description": "Verify API endpoint connectivity and response times on user_history screen", "key": "historyNavVisible", "category": "API Testing" },
  { "id": "TC097", "description": "Verify SQLite/indexedDB persistence state when navigating user_history screen", "key": "historyNavVisible", "category": "Database Testing" },
  { "id": "TC098", "description": "Verify talkback announcements and accessible name tag targets for user_history screen", "key": "historyNavVisible", "category": "Accessibility Testing" },
  { "id": "TC099", "description": "Verify mobile OS notification hooks and system interaction on user_history screen", "key": "historyNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC100", "description": "Full Flow: E2E regression check covering user_history screen features", "key": "historyNavVisible", "category": "End-to-End Testing" },
  { "id": "TC101", "description": "Verify app launch to user_issue_details?id=123 screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC102", "description": "Verify text contrast and font styling consistency on user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC103", "description": "Verify compatibility of user_issue_details?id=123 screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC104", "description": "Measure memory utilization on cold start of user_issue_details?id=123 mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC105", "description": "Verify local encrypted storage for inputs related to user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC106", "description": "Verify API endpoint connectivity and response times on user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC107", "description": "Verify SQLite/indexedDB persistence state when navigating user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC108", "description": "Verify talkback announcements and accessible name tag targets for user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC109", "description": "Verify mobile OS notification hooks and system interaction on user_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC110", "description": "Full Flow: E2E regression check covering user_issue_details?id=123 screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC111", "description": "Verify app launch to chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC112", "description": "Verify text contrast and font styling consistency on chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC113", "description": "Verify compatibility of chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC114", "description": "Measure memory utilization on cold start of chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC115", "description": "Verify local encrypted storage for inputs related to chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC116", "description": "Verify API endpoint connectivity and response times on chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC117", "description": "Verify SQLite/indexedDB persistence state when navigating chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC118", "description": "Verify talkback announcements and accessible name tag targets for chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC119", "description": "Verify mobile OS notification hooks and system interaction on chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC120", "description": "Full Flow: E2E regression check covering chat?viewer=user&org_id=456&org_name=Hospital&user_id=123 screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC121", "description": "Verify app launch to messages_list screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC122", "description": "Verify text contrast and font styling consistency on messages_list screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC123", "description": "Verify compatibility of messages_list screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC124", "description": "Measure memory utilization on cold start of messages_list mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC125", "description": "Verify local encrypted storage for inputs related to messages_list screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC126", "description": "Verify API endpoint connectivity and response times on messages_list screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC127", "description": "Verify SQLite/indexedDB persistence state when navigating messages_list screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC128", "description": "Verify talkback announcements and accessible name tag targets for messages_list screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC129", "description": "Verify mobile OS notification hooks and system interaction on messages_list screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC130", "description": "Full Flow: E2E regression check covering messages_list screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC131", "description": "Verify app launch to user_profile screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC132", "description": "Verify text contrast and font styling consistency on user_profile screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC133", "description": "Verify compatibility of user_profile screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC134", "description": "Measure memory utilization on cold start of user_profile mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC135", "description": "Verify local encrypted storage for inputs related to user_profile screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC136", "description": "Verify API endpoint connectivity and response times on user_profile screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC137", "description": "Verify SQLite/indexedDB persistence state when navigating user_profile screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC138", "description": "Verify talkback announcements and accessible name tag targets for user_profile screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC139", "description": "Verify mobile OS notification hooks and system interaction on user_profile screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC140", "description": "Full Flow: E2E regression check covering user_profile screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC141", "description": "Verify app launch to user_account_details screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC142", "description": "Verify text contrast and font styling consistency on user_account_details screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC143", "description": "Verify compatibility of user_account_details screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC144", "description": "Measure memory utilization on cold start of user_account_details mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC145", "description": "Verify local encrypted storage for inputs related to user_account_details screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC146", "description": "Verify API endpoint connectivity and response times on user_account_details screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC147", "description": "Verify SQLite/indexedDB persistence state when navigating user_account_details screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC148", "description": "Verify talkback announcements and accessible name tag targets for user_account_details screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC149", "description": "Verify mobile OS notification hooks and system interaction on user_account_details screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC150", "description": "Full Flow: E2E regression check covering user_account_details screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC151", "description": "Verify app launch to user_ai screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC152", "description": "Verify text contrast and font styling consistency on user_ai screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC153", "description": "Verify compatibility of user_ai screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC154", "description": "Measure memory utilization on cold start of user_ai mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC155", "description": "Verify local encrypted storage for inputs related to user_ai screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC156", "description": "Verify API endpoint connectivity and response times on user_ai screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC157", "description": "Verify SQLite/indexedDB persistence state when navigating user_ai screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC158", "description": "Verify talkback announcements and accessible name tag targets for user_ai screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC159", "description": "Verify mobile OS notification hooks and system interaction on user_ai screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC160", "description": "Full Flow: E2E regression check covering user_ai screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC161", "description": "Verify app launch to user_reset_password screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC162", "description": "Verify text contrast and font styling consistency on user_reset_password screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC163", "description": "Verify compatibility of user_reset_password screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC164", "description": "Measure memory utilization on cold start of user_reset_password mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC165", "description": "Verify local encrypted storage for inputs related to user_reset_password screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC166", "description": "Verify API endpoint connectivity and response times on user_reset_password screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC167", "description": "Verify SQLite/indexedDB persistence state when navigating user_reset_password screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC168", "description": "Verify talkback announcements and accessible name tag targets for user_reset_password screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC169", "description": "Verify mobile OS notification hooks and system interaction on user_reset_password screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC170", "description": "Full Flow: E2E regression check covering user_reset_password screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC171", "description": "Verify app launch to user_help screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC172", "description": "Verify text contrast and font styling consistency on user_help screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC173", "description": "Verify compatibility of user_help screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC174", "description": "Measure memory utilization on cold start of user_help mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC175", "description": "Verify local encrypted storage for inputs related to user_help screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC176", "description": "Verify API endpoint connectivity and response times on user_help screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC177", "description": "Verify SQLite/indexedDB persistence state when navigating user_help screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC178", "description": "Verify talkback announcements and accessible name tag targets for user_help screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC179", "description": "Verify mobile OS notification hooks and system interaction on user_help screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC180", "description": "Full Flow: E2E regression check covering user_help screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC181", "description": "Verify app launch to user_privacy screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC182", "description": "Verify text contrast and font styling consistency on user_privacy screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC183", "description": "Verify compatibility of user_privacy screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC184", "description": "Measure memory utilization on cold start of user_privacy mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC185", "description": "Verify local encrypted storage for inputs related to user_privacy screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC186", "description": "Verify API endpoint connectivity and response times on user_privacy screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC187", "description": "Verify SQLite/indexedDB persistence state when navigating user_privacy screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC188", "description": "Verify talkback announcements and accessible name tag targets for user_privacy screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC189", "description": "Verify mobile OS notification hooks and system interaction on user_privacy screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC190", "description": "Full Flow: E2E regression check covering user_privacy screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC191", "description": "Verify app launch to org_login screen transition on Android", "key": "loginEmailVisible", "category": "Functional Testing" },
  { "id": "TC192", "description": "Verify text contrast and font styling consistency on org_login screen", "key": "loginEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC193", "description": "Verify compatibility of org_login screen layout with small mobile aspect ratios", "key": "loginEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC194", "description": "Measure memory utilization on cold start of org_login mobile screen", "key": "loginEmailVisible", "category": "Performance Testing" },
  { "id": "TC195", "description": "Verify local encrypted storage for inputs related to org_login screen", "key": "loginEmailVisible", "category": "Security Testing" },
  { "id": "TC196", "description": "Verify API endpoint connectivity and response times on org_login screen", "key": "loginEmailVisible", "category": "API Testing" },
  { "id": "TC197", "description": "Verify SQLite/indexedDB persistence state when navigating org_login screen", "key": "loginEmailVisible", "category": "Database Testing" },
  { "id": "TC198", "description": "Verify talkback announcements and accessible name tag targets for org_login screen", "key": "loginEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC199", "description": "Verify mobile OS notification hooks and system interaction on org_login screen", "key": "loginEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC200", "description": "Full Flow: E2E regression check covering org_login screen features", "key": "loginEmailVisible", "category": "End-to-End Testing" },
  { "id": "TC201", "description": "Verify app launch to org_signup screen transition on Android", "key": "navigateToSignup", "category": "Functional Testing" },
  { "id": "TC202", "description": "Verify text contrast and font styling consistency on org_signup screen", "key": "navigateToSignup", "category": "UI/UX Testing" },
  { "id": "TC203", "description": "Verify compatibility of org_signup screen layout with small mobile aspect ratios", "key": "navigateToSignup", "category": "Compatibility Testing" },
  { "id": "TC204", "description": "Measure memory utilization on cold start of org_signup mobile screen", "key": "navigateToSignup", "category": "Performance Testing" },
  { "id": "TC205", "description": "Verify local encrypted storage for inputs related to org_signup screen", "key": "navigateToSignup", "category": "Security Testing" },
  { "id": "TC206", "description": "Verify API endpoint connectivity and response times on org_signup screen", "key": "navigateToSignup", "category": "API Testing" },
  { "id": "TC207", "description": "Verify SQLite/indexedDB persistence state when navigating org_signup screen", "key": "navigateToSignup", "category": "Database Testing" },
  { "id": "TC208", "description": "Verify talkback announcements and accessible name tag targets for org_signup screen", "key": "navigateToSignup", "category": "Accessibility Testing" },
  { "id": "TC209", "description": "Verify mobile OS notification hooks and system interaction on org_signup screen", "key": "navigateToSignup", "category": "Mobile-Specific Testing" },
  { "id": "TC210", "description": "Full Flow: E2E regression check covering org_signup screen features", "key": "navigateToSignup", "category": "End-to-End Testing" },
  { "id": "TC211", "description": "Verify app launch to org_forgot_password screen transition on Android", "key": "resetEmailVisible", "category": "Functional Testing" },
  { "id": "TC212", "description": "Verify text contrast and font styling consistency on org_forgot_password screen", "key": "resetEmailVisible", "category": "UI/UX Testing" },
  { "id": "TC213", "description": "Verify compatibility of org_forgot_password screen layout with small mobile aspect ratios", "key": "resetEmailVisible", "category": "Compatibility Testing" },
  { "id": "TC214", "description": "Measure memory utilization on cold start of org_forgot_password mobile screen", "key": "resetEmailVisible", "category": "Performance Testing" },
  { "id": "TC215", "description": "Verify local encrypted storage for inputs related to org_forgot_password screen", "key": "resetEmailVisible", "category": "Security Testing" },
  { "id": "TC216", "description": "Verify API endpoint connectivity and response times on org_forgot_password screen", "key": "resetEmailVisible", "category": "API Testing" },
  { "id": "TC217", "description": "Verify SQLite/indexedDB persistence state when navigating org_forgot_password screen", "key": "resetEmailVisible", "category": "Database Testing" },
  { "id": "TC218", "description": "Verify talkback announcements and accessible name tag targets for org_forgot_password screen", "key": "resetEmailVisible", "category": "Accessibility Testing" },
  { "id": "TC219", "description": "Verify mobile OS notification hooks and system interaction on org_forgot_password screen", "key": "resetEmailVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC220", "description": "Full Flow: E2E regression check covering org_forgot_password screen features", "key": "resetEmailVisible", "category": "End-to-End Testing" },
  { "id": "TC221", "description": "Verify app launch to org_dashboard screen transition on Android", "key": "dashboardReportCountVisible", "category": "Functional Testing" },
  { "id": "TC222", "description": "Verify text contrast and font styling consistency on org_dashboard screen", "key": "dashboardReportCountVisible", "category": "UI/UX Testing" },
  { "id": "TC223", "description": "Verify compatibility of org_dashboard screen layout with small mobile aspect ratios", "key": "dashboardReportCountVisible", "category": "Compatibility Testing" },
  { "id": "TC224", "description": "Measure memory utilization on cold start of org_dashboard mobile screen", "key": "dashboardReportCountVisible", "category": "Performance Testing" },
  { "id": "TC225", "description": "Verify local encrypted storage for inputs related to org_dashboard screen", "key": "dashboardReportCountVisible", "category": "Security Testing" },
  { "id": "TC226", "description": "Verify API endpoint connectivity and response times on org_dashboard screen", "key": "dashboardReportCountVisible", "category": "API Testing" },
  { "id": "TC227", "description": "Verify SQLite/indexedDB persistence state when navigating org_dashboard screen", "key": "dashboardReportCountVisible", "category": "Database Testing" },
  { "id": "TC228", "description": "Verify talkback announcements and accessible name tag targets for org_dashboard screen", "key": "dashboardReportCountVisible", "category": "Accessibility Testing" },
  { "id": "TC229", "description": "Verify mobile OS notification hooks and system interaction on org_dashboard screen", "key": "dashboardReportCountVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC230", "description": "Full Flow: E2E regression check covering org_dashboard screen features", "key": "dashboardReportCountVisible", "category": "End-to-End Testing" },
  { "id": "TC231", "description": "Verify app launch to org_issues screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC232", "description": "Verify text contrast and font styling consistency on org_issues screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC233", "description": "Verify compatibility of org_issues screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC234", "description": "Measure memory utilization on cold start of org_issues mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC235", "description": "Verify local encrypted storage for inputs related to org_issues screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC236", "description": "Verify API endpoint connectivity and response times on org_issues screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC237", "description": "Verify SQLite/indexedDB persistence state when navigating org_issues screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC238", "description": "Verify talkback announcements and accessible name tag targets for org_issues screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC239", "description": "Verify mobile OS notification hooks and system interaction on org_issues screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC240", "description": "Full Flow: E2E regression check covering org_issues screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC241", "description": "Verify app launch to org_completed screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC242", "description": "Verify text contrast and font styling consistency on org_completed screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC243", "description": "Verify compatibility of org_completed screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC244", "description": "Measure memory utilization on cold start of org_completed mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC245", "description": "Verify local encrypted storage for inputs related to org_completed screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC246", "description": "Verify API endpoint connectivity and response times on org_completed screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC247", "description": "Verify SQLite/indexedDB persistence state when navigating org_completed screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC248", "description": "Verify talkback announcements and accessible name tag targets for org_completed screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC249", "description": "Verify mobile OS notification hooks and system interaction on org_completed screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC250", "description": "Full Flow: E2E regression check covering org_completed screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC251", "description": "Verify app launch to org_issue_details?id=123 screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC252", "description": "Verify text contrast and font styling consistency on org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC253", "description": "Verify compatibility of org_issue_details?id=123 screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC254", "description": "Measure memory utilization on cold start of org_issue_details?id=123 mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC255", "description": "Verify local encrypted storage for inputs related to org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC256", "description": "Verify API endpoint connectivity and response times on org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC257", "description": "Verify SQLite/indexedDB persistence state when navigating org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC258", "description": "Verify talkback announcements and accessible name tag targets for org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC259", "description": "Verify mobile OS notification hooks and system interaction on org_issue_details?id=123 screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC260", "description": "Full Flow: E2E regression check covering org_issue_details?id=123 screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC261", "description": "Verify app launch to org_profile screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC262", "description": "Verify text contrast and font styling consistency on org_profile screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC263", "description": "Verify compatibility of org_profile screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC264", "description": "Measure memory utilization on cold start of org_profile mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC265", "description": "Verify local encrypted storage for inputs related to org_profile screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC266", "description": "Verify API endpoint connectivity and response times on org_profile screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC267", "description": "Verify SQLite/indexedDB persistence state when navigating org_profile screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC268", "description": "Verify talkback announcements and accessible name tag targets for org_profile screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC269", "description": "Verify mobile OS notification hooks and system interaction on org_profile screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC270", "description": "Full Flow: E2E regression check covering org_profile screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC271", "description": "Verify app launch to org_settings screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC272", "description": "Verify text contrast and font styling consistency on org_settings screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC273", "description": "Verify compatibility of org_settings screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC274", "description": "Measure memory utilization on cold start of org_settings mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC275", "description": "Verify local encrypted storage for inputs related to org_settings screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC276", "description": "Verify API endpoint connectivity and response times on org_settings screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC277", "description": "Verify SQLite/indexedDB persistence state when navigating org_settings screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC278", "description": "Verify talkback announcements and accessible name tag targets for org_settings screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC279", "description": "Verify mobile OS notification hooks and system interaction on org_settings screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC280", "description": "Full Flow: E2E regression check covering org_settings screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC281", "description": "Verify app launch to org_reset_password screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC282", "description": "Verify text contrast and font styling consistency on org_reset_password screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC283", "description": "Verify compatibility of org_reset_password screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC284", "description": "Measure memory utilization on cold start of org_reset_password mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC285", "description": "Verify local encrypted storage for inputs related to org_reset_password screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC286", "description": "Verify API endpoint connectivity and response times on org_reset_password screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC287", "description": "Verify SQLite/indexedDB persistence state when navigating org_reset_password screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC288", "description": "Verify talkback announcements and accessible name tag targets for org_reset_password screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC289", "description": "Verify mobile OS notification hooks and system interaction on org_reset_password screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC290", "description": "Full Flow: E2E regression check covering org_reset_password screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC291", "description": "Verify app launch to org_help screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC292", "description": "Verify text contrast and font styling consistency on org_help screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC293", "description": "Verify compatibility of org_help screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC294", "description": "Measure memory utilization on cold start of org_help mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC295", "description": "Verify local encrypted storage for inputs related to org_help screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC296", "description": "Verify API endpoint connectivity and response times on org_help screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC297", "description": "Verify SQLite/indexedDB persistence state when navigating org_help screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC298", "description": "Verify talkback announcements and accessible name tag targets for org_help screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC299", "description": "Verify mobile OS notification hooks and system interaction on org_help screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC300", "description": "Full Flow: E2E regression check covering org_help screen features", "key": "profileNavVisible", "category": "End-to-End Testing" },
  { "id": "TC301", "description": "Verify app launch to org_privacy screen transition on Android", "key": "profileNavVisible", "category": "Functional Testing" },
  { "id": "TC302", "description": "Verify text contrast and font styling consistency on org_privacy screen", "key": "profileNavVisible", "category": "UI/UX Testing" },
  { "id": "TC303", "description": "Verify compatibility of org_privacy screen layout with small mobile aspect ratios", "key": "profileNavVisible", "category": "Compatibility Testing" },
  { "id": "TC304", "description": "Measure memory utilization on cold start of org_privacy mobile screen", "key": "profileNavVisible", "category": "Performance Testing" },
  { "id": "TC305", "description": "Verify local encrypted storage for inputs related to org_privacy screen", "key": "profileNavVisible", "category": "Security Testing" },
  { "id": "TC306", "description": "Verify API endpoint connectivity and response times on org_privacy screen", "key": "profileNavVisible", "category": "API Testing" },
  { "id": "TC307", "description": "Verify SQLite/indexedDB persistence state when navigating org_privacy screen", "key": "profileNavVisible", "category": "Database Testing" },
  { "id": "TC308", "description": "Verify talkback announcements and accessible name tag targets for org_privacy screen", "key": "profileNavVisible", "category": "Accessibility Testing" },
  { "id": "TC309", "description": "Verify mobile OS notification hooks and system interaction on org_privacy screen", "key": "profileNavVisible", "category": "Mobile-Specific Testing" },
  { "id": "TC310", "description": "Full Flow: E2E regression check covering org_privacy screen features", "key": "profileNavVisible", "category": "End-to-End Testing" }
]